export const stylesNames = {
  root: "root",
  cardTop: "card__top",
  cardInfo: "card__info",
  cardMiddle: "card__middle",
  cardInner: "card__inner",
  tools: "tools",
  logo: "logo",
  cardInnerInfo: "card__inner-info",
  linkContainer: "link-container",
  title: "title",
  tooltip: "tooltip",
  copyButton: "copy-button",
  cardAircraftType: "card__aircraft-type",
};
